baseURL = '/'
defaultContentLanguage = "id"
languageCode = "id"
title = 'Link Bio &#64;Cats'
disableHugoGeneratorInject = false
PygmentsCodeFences = false
PygmentsStyle = "none"
pluralizelisttitles = "false"
enableRobotsTXT = true
enableEmoji = false
disableKinds = ["RSS","term","taxonomy","sitemap","404"]


[taxonomies]
category = "categories"
tag = "tags"

[params]
logo = "/svg/logo.svg"
favicon = "/svg/logo.svg"


